[package]
name = "widget_renderer"
version = "0.1.3"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rutie = "0.9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
